// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schulbibliothek.Data;

#nullable disable

namespace Schulbibliothek.Migrations
{
    [DbContext(typeof(SchulbibliothekDbContext))]
    [Migration("20260226120931_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Schulbibliothek.Models.Buch", b =>
                {
                    b.Property<int>("BuchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuchId"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("istVerfuegbar")
                        .HasColumnType("bit");

                    b.HasKey("BuchId");

                    b.ToTable("Buecher");
                });

            modelBuilder.Entity("Schulbibliothek.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Bild")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Personen");
                });

            modelBuilder.Entity("Schulbibliothek.Models.Transaktion", b =>
                {
                    b.Property<int>("TransaktionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransaktionId"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BuchId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<bool>("istAusgeliehen")
                        .HasColumnType("bit");

                    b.HasKey("TransaktionId");

                    b.HasIndex("BuchId");

                    b.HasIndex("PersonId");

                    b.ToTable("Transaktionen");
                });

            modelBuilder.Entity("Schulbibliothek.Models.Transaktion", b =>
                {
                    b.HasOne("Schulbibliothek.Models.Buch", "Buch")
                        .WithMany("Transaktionen")
                        .HasForeignKey("BuchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schulbibliothek.Models.Person", "Person")
                        .WithMany("Transaktionen")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buch");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Schulbibliothek.Models.Buch", b =>
                {
                    b.Navigation("Transaktionen");
                });

            modelBuilder.Entity("Schulbibliothek.Models.Person", b =>
                {
                    b.Navigation("Transaktionen");
                });
#pragma warning restore 612, 618
        }
    }
}
